let defaultConfig = require('tailwindcss/defaultConfig')()
var cssberriesColors = require("cssberries-colors");
let colors = cssberriesColors.colorsGenerator.generateColors(12, 4);
module.exports = {
    screens: {
        'sm': '576px',
        'md': '768px',
        'lg': '992px',
        'xl': '1200px',
    },
    fonts: {
        'sans': [
            'system-ui',
            'BlinkMacSystemFont',
            '-apple-system',
            'Segoe UI',
            'Roboto',
            'Oxygen',
            'Ubuntu',
            'Cantarell',
            'Fira Sans',
            'Droid Sans',
            'Helvetica Neue',
            'sans-serif',
        ],
        'serif': [
            'Constantia',
            'Lucida Bright',
            'Lucidabright',
            'Lucida Serif',
            'Lucida',
            'DejaVu Serif',
            'Bitstream Vera Serif',
            'Liberation Serif',
            'Georgia',
            'serif',
        ],
        'mono': [
            'Menlo',
            'Monaco',
            'Consolas',
            'Liberation Mono',
            'Courier New',
            'monospace',
        ],
    },
    textSizes: {
        '2xs': '.6rem',
        'xs': '.75rem',
        'sm': '.875rem',
        'md': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
    },
    fontWeights: {
        'hairline': 100,
        'thin': 200,
        'light': 300,
        'normal': 400,
        'medium': 500,
        'semibold': 600,
        'bold': 700,
        'extrabold': 800,
        'black': 900,
    },
    textColors: {
        'color-weakest': 'var(--text-color-weakest)',
        'color-weaker': 'var(--text-color-weaker)',
        'color-weak': 'var(--text-color-weak)',
        'color-medium': 'var(--text-color-medium)',
        'color-strong': 'var(--text-color-strong)',
        'color-stronger': 'var(--text-color-stronger)',
        'color-strongest': 'var(--text-color-strongest)'
    },
    backgroundColors: {
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'accent': 'var(--color-accent)',
        // 
        'canvas': 'var(--color-canvas)',
        'aside': 'var(--color-aside)',
        'content': 'var(--color-content)',
        // 
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
        // 
        'info': 'var(--color-info)',
        'selected': 'var(--color-selected)',
        'temporary': 'var(--color-info)'

    },
    backgroundSize: {
        'auto': 'auto',
        'cover': 'cover',
        'contain': 'contain',
    },
    borderWidths: {
        default: '1px',
        '0': '0',
        'bold': '2px',
        'bolder': '3px',
        'boldest': '5px',
    },
    borderColors: {},
    borderRadius: {
        default: '3px',
        'none': '0',
        'smallest': '1px',
        'small': '2px',
        'medium': '3px',
        'large': '5px',
        'largest': '8px',
        'full': '100em'
    },
    width: {
        'auto': 'auto',
        'px': '1px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
        '32': '8rem',
        '48': '12rem',
        '64': '16rem',
        '1/2': '50%',
        '1/3': '33.33333%',
        '2/3': '66.66667%',
        '1/4': '25%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.66667%',
        '5/6': '83.33333%',
        'full': '100%',
        'screen': '100vw',
    },
    height: {
        'auto': 'auto',
        'px': '1px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
        '32': '8rem',
        '48': '12rem',
        '64': '16rem',
        'full': '100%',
        'screen': '100vh',
    },
    minWidth: {
        '0': '0',
        'full': '100%',
    },
    minHeight: {
        '0': '0',
        'full': '100%',
        'screen': '100vh',
    },
    maxWidth: {
        'xs': '20rem',
        'sm': '30rem',
        'md': '40rem',
        'lg': '50rem',
        'xl': '60rem',
        '2xl': '70rem',
        '3xl': '80rem',
        '4xl': '90rem',
        '5xl': '100rem',
        'full': '100%',
    },
    maxHeight: {
        'full': '100%',
        'screen': '100vh',
    },
    padding: {
        'px': '1px',
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
    },
    margin: {
        'auto': 'auto',
        'px': '1px',
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
    },
    negativeMargin: {
        'px': '1px',
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
    },
    shadows: {
        default: '0 2px 4px 0 rgba(0,0,0,0.10)',
        'md': '0 4px 8px 0 rgba(0,0,0,0.12), 0 2px 4px 0 rgba(0,0,0,0.08)',
        'lg': '0 15px 30px 0 rgba(0,0,0,0.11), 0 5px 15px 0 rgba(0,0,0,0.08)',
        'inner': 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
        'outline': '0 0 0 3px rgba(52,144,220,0.5)',
        'none': 'none',
    },
    zIndex: {
        'auto': 'auto',
        '0': 0,
        '10': 10,
        '20': 20,
        '30': 30,
        '40': 40,
        '50': 50,
    },
    opacity: {
        '0': '0',
        '25': '.25',
        '50': '.5',
        '75': '.75',
        '100': '1',
    },
    svgFill: {
        'current': 'currentColor',
    },
    svgStroke: {
        'current': 'currentColor',
    },
    modules: {
        appearance: false,
        backgroundAttachment: false,
        backgroundColors: [],
        backgroundPosition: false,
        backgroundRepeat: false,
        backgroundSize: false,
        borderCollapse: false,
        borderColors: [],
        borderRadius: [],
        borderStyle: [],
        borderWidths: [],
        cursor: false,
        display: false,
        flexbox: [],
        float: false,
        fonts: false,
        fontWeights: false,
        height: false,
        leading: false,
        lists: false,
        margin: [],
        maxHeight: false,
        maxWidth: false,
        minHeight: false,
        minWidth: [],
        negativeMargin: false,
        objectFit: false,
        objectPosition: false,
        opacity: [],
        outline: false,
        overflow: [],
        padding: [],
        pointerEvents: [],
        position: [],
        resize: [],
        shadows: [],
        svgFill: [],
        svgStroke: [],
        tableLayout: false,
        textAlign: false,
        textColors: [],
        textSizes: [],
        textStyle: false,
        tracking: false,
        userSelect: false,
        verticalAlign: false,
        visibility: [],
        whitespace: false,
        width: [],
        zIndex: [],
    },


    /*
    |-----------------------------------------------------------------------------
    | Plugins                                https://tailwindcss.com/docs/plugins
    |-----------------------------------------------------------------------------
    |
    | Here is where you can register any plugins you'd like to use in your
    | project. Tailwind's built-in `container` plugin is enabled by default to
    | give you a Bootstrap-style responsive container component out of the box.
    |
    | Be sure to view the complete plugin documentation to learn more about how
    | the plugin system works.
    |
    */

    plugins: [
        require('tailwindcss/plugins/container')({
            center: true,
            // padding: '1rem',
        }),
    ],


    /*
    |-----------------------------------------------------------------------------
    | Advanced Options         https://tailwindcss.com/docs/configuration#options
    |-----------------------------------------------------------------------------
    |
    | Here is where you can tweak advanced configuration options. We recommend
    | leaving these options alone unless you absolutely need to change them.
    |
    */

    options: {
        prefix: '',
        important: false,
        separator: ':',
    },

}